random_seed: 42
shuffle: true
components:
- type: cluster
  n_points: 200
  center:
  - 2
  - 2
  scale: 0.5
- type: ring
  n_points: 150
  center:
  - 6
  - 6
  radius: 2
  thickness: 0.2
- type: line
  n_points: 100
  start:
  - 0
  - 0
  end:
  - 5
  - 5
  thickness: 0.3
- type: noise
  n_points: 50
  min: 0
  max: 10
  dimensions: 2
description: Example dataset with multiple component types
