# Grid dataset configuration
# Regular grid of points with some noise, suitable for testing grid selection algorithms

random_seed: 42
shuffle: true

components:
  # Create a grid of 10x10 clusters
  - type: grid
    n_points: 50  # Points per grid cell
    grid_size: [10, 10]  # 10x10 grid
    min_coords: [0, 0]
    max_coords: [10, 10]
    cluster_scale: 0.1  # Small clusters at each grid point
    
  # Add some noise
  - type: noise
    n_points: 200
    min: 0
    max: 10
    dimensions: 2

description: Regular grid of points with some noise, suitable for testing grid selection algorithms

# Custom component type 'grid' implementation
# This will be handled specially in the data generator 